# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
	v.cpus = 2
    v.memory = 1024
  end

  config.vm.provision "shell", path: "provisioning.sh"

  config.vm.network "forwarded_port", guest: 22, host:10022, id: "ssh", auto_correct: false
end
